name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

env:
  DOCKER_IMAGE: abou12345/php-mysql-combine:latest  # Docker Hub username and repository name

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout  repository

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in secrets

      - name: Build the Docker image
        run: |
          docker build -t $DOCKER_IMAGE .  # Build the Docker image from the Dockerfile in the repository

      - name: Push the Docker image to Docker Hub
        run: |
          docker push $DOCKER_IMAGE  # Push the built Docker image to Docker Hub
