name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub token stored in GitHub Secrets

      - name: Build the Docker image
        run: |
          docker build  -t abou12345/php-mysql-combine:latest 

      - name: Push the Docker image to Docker Hub
        run: |
          docker push abou12345/php-mysql-combine:latest
