name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: abou12345  # Docker Hub username (replace with your Docker Hub username)
          DOCKER_PASSWORD: dckr_pat_2ixH8zs3oZenVoQFOLEADQdagWk  # Docker Hub access token (replace with your PAT)

      - name: Build the Docker image
        run: |
          docker build -t abou12345/php-mysql-combine:latest .  # Build the Docker image

      - name: Push the Docker image to Docker Hub
        run: |
          docker push abou12345/php-mysql-combine:latest  # Push the Docker image to Docker Hub

